-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-30 17:00:26 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
CREATE TABLE schema_audit
  (
    ddl_date       DATE,
    ddl_user       VARCHAR2(15),
    object_created VARCHAR2(15),
    object_name    VARCHAR2(15),
    ddl_operation  VARCHAR2(15)
  );

CREATE TABLE address (
    address_id    Integer NOT NULL,
    street        VARCHAR2(40) NOT NULL,
    postal_code   VARCHAR2(10) NOT NULL,
    city_city_id  INTEGER NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE city (
    city_id             INTEGER NOT NULL,
    city_name           VARCHAR2(50) NOT NULL,
    country_country_id  INTEGER NOT NULL
);

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_id );

CREATE TABLE country (
    country_id    INTEGER NOT NULL,
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_id );

CREATE TABLE department (
    department_id    INTEGER NOT NULL,
    department_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( department_id );

CREATE TABLE employee (
    employee_id           INTEGER NOT NULL,
    first_name            VARCHAR2(25) NOT NULL,
    last_name             VARCHAR2(25) NOT NULL,
    birth_date            DATE NOT NULL,
    gender                CHAR(1) NOT NULL,
    email                 CHAR(40) NOT NULL,
    position_position_id  INTEGER NOT NULL,
    address_address_id    INTEGER NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE employment_history (
    emp_dept_id               INTEGER NOT NULL,
    salary                    NUMBER NOT NULL,
    start_date                DATE NOT NULL,
    end_date                  DATE,
    employee_employee_id      INTEGER NOT NULL,
    department_department_id  INTEGER NOT NULL
);

ALTER TABLE employment_history ADD CONSTRAINT employment_history_pk PRIMARY KEY ( emp_dept_id );

CREATE TABLE position (
    position_id    INTEGER NOT NULL,
    position_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE position ADD CONSTRAINT position_pk PRIMARY KEY ( position_id );

ALTER TABLE address
    ADD CONSTRAINT address_city_fk FOREIGN KEY ( city_city_id )
        REFERENCES city ( city_id );

ALTER TABLE city
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( country_country_id )
        REFERENCES country ( country_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_address_fk FOREIGN KEY ( address_address_id )
        REFERENCES address ( address_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_position_fk FOREIGN KEY ( position_position_id )
        REFERENCES position ( position_id );

ALTER TABLE employment_history
    ADD CONSTRAINT emp_hist_department_fk FOREIGN KEY ( department_department_id )
        REFERENCES department ( department_id );

ALTER TABLE employment_history
    ADD CONSTRAINT emp_hist_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );


CREATE SEQUENCE SEQ_ADDRESS
START WITH 1
INCREMENT BY 1
ORDER;

CREATE SEQUENCE SEQ_CITY
START WITH 1
INCREMENT BY 1
ORDER;

CREATE SEQUENCE SEQ_COUNTRY
START WITH 1
INCREMENT BY 1
ORDER;

CREATE SEQUENCE SEQ_DEPARTMENT
START WITH 1
INCREMENT BY 1
ORDER;

CREATE SEQUENCE SEQ_EMPLOYEE
START WITH 1
INCREMENT BY 1
ORDER;

CREATE SEQUENCE SEQ_EMPLOYMENT_HISTORY
START WITH 1
INCREMENT BY 1
ORDER;

CREATE SEQUENCE SEQ_POSITION
START WITH 1
INCREMENT BY 1
ORDER;