-- Country Table
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'Australia');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'China');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'England');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'Germany');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'India');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'Japan');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'Poland');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'Russia');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'Spain');
INSERT INTO Country VALUES(SEQ_COUNTRY.NEXTVAL, 'United States');


-- City Table
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Sydney', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Beijing', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'London', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Berlin', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Delhi', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Tokyo', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Lodz', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Moscow', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'Barcelona', SEQ_CITY.CURRVAL);
INSERT INTO City VALUES(SEQ_CITY.NEXTVAL, 'New York', SEQ_CITY.CURRVAL);


-- Address Table
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, '3 Doris St, North Sydney', 'NSW 2060', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'hang Hai Shi Lin Gang Xin Cheng Hu Cheng','LP 4567', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, '60  Ballifeary Road', 'OX16 3FF', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'Genslerstrae 84', '13359', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'G 29, I J Complex, Subhash Chowk','110092', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'Marunochi Gurantokyo Sausutawa(19-kai)','100-6619', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'Matejki 21/23 ','90-447',SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'Chupanovskaya Ul., bld. 79', '785-68', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, 'Comandante Izarduy 67','08940', SEQ_ADDRESS.CURRVAL);
INSERT INTO Address VALUES(SEQ_ADDRESS.NEXTVAL, '3111  Angus Road', '10014', SEQ_ADDRESS.CURRVAL);


-- Department Table
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Accounting');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Administration');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Executive');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Finance');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Human Resources');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'IT');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Marketing');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Public Relations');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Purchasing');
INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Shipping');


-- Position table
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Accountant');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Administration Assistant');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'President');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Finance Manager');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Human Resources Representative');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Programmer');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Marketing Manager');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Public Relations Representative');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Sales Manager');
INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Shipping Clerk');


-- Employee Table
INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Filiph', 'Miller',TO_DATE
('09/12/1977','dd/mm/yyyy'),'M','FMILLER@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Henry', 'Bell',TO_DATE
('11/02/1993','dd/mm/yyyy'),'M','HBELL@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'James', 'Collins',TO_DATE
('09/12/1983','dd/mm/yyyy'),'M','JCOLLINS@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Adrien', 'Powell',TO_DATE
('09/12/2000','dd/mm/yyyy'),'M','APOWELL@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Albert', 'Foster',TO_DATE
('09/12/1999','dd/mm/yyyy'),'M','AFOSTER@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Alice', 'Adams',TO_DATE
('09/12/1992','dd/mm/yyyy'),'F','AADAMS@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Eva', 'Owen',TO_DATE
('09/12/1994','dd/mm/yyyy'),'F','EOWEN@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Hannah', 'Mills',TO_DATE
('09/12/1998','dd/mm/yyyy'),'F','HMILLS@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Justina', 'Stevens',TO_DATE
('09/12/1999','dd/mm/yyyy'),'F','JSTEVENS@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);

INSERT INTO Employee VALUES(SEQ_EMPLOYEE.NEXTVAL, 'Laura', 'Fisher',TO_DATE
('09/12/1977','dd/mm/yyyy'),'F','LFISHER@COMPEDU.EU',SEQ_EMPLOYEE.CURRVAL, SEQ_EMPLOYEE.CURRVAL);


-- Employment History Table
INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 1500, TO_DATE
('16/09/2005','dd/mm/yyyy'),NULL,SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 1700, TO_DATE
('23/07/2002','dd/mm/yyyy'),TO_DATE('24/05/2004','dd/mm/yyyy'),SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 3000, TO_DATE
('14/02/2000','dd/mm/yyyy'),NULL,SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 2300, TO_DATE
('24/03/2002','dd/mm/yyyy'),TO_DATE('24/05/2005','dd/mm/yyyy'),SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 2100, TO_DATE
('08/04/2004','dd/mm/yyyy'),NULL,SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 2500, TO_DATE
('13/12/2002','dd/mm/yyyy'),TO_DATE('23/05/2009','dd/mm/yyyy'),SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 2000, TO_DATE
('19/06/2003','dd/mm/yyyy'),NULL,SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 1800, TO_DATE
('18/11/2004','dd/mm/yyyy'),TO_DATE('23/04/2008','dd/mm/yyyy'),SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 1500, TO_DATE
('03/03/2003','dd/mm/yyyy'),NULL,SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);

INSERT INTO Employment_history VALUES(SEQ_EMPLOYMENT_HISTORY.NEXTVAL, 1300, TO_DATE
('17/01/2001','dd/mm/yyyy'),TO_DATE('20/08/2010','dd/mm/yyyy'),SEQ_EMPLOYMENT_HISTORY.CURRVAL,SEQ_EMPLOYMENT_HISTORY.CURRVAL);


-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Treasury');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Corporate Tax');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Control And Credit');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Benefits');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Manufacturing');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Construction');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Contracting');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Operations');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'IT Support');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'NOC');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'IT Helpdesk');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Government Sales');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Retail Sales');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Recruiting');
-- INSERT INTO Department VALUES(SEQ_DEPARTMENT.NEXTVAL, 'Payroll');

-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Public Accountant');
-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Marketing Representative');
-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Sales Representative');
-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Stock Manager');
-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Accounting Manager');
-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Administration Vice President');
-- INSERT INTO Position VALUES(SEQ_Position.NEXTVAL, 'Stock Clerk');