-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-30 17:00:26 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE address (
    address_id    Integer NOT NULL,
    street        VARCHAR2(40) NOT NULL,
    postal_code   VARCHAR2(10) NOT NULL,
    city_city_id  INTEGER NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE city (
    city_id             INTEGER NOT NULL,
    city_name           VARCHAR2(50) NOT NULL,
    country_country_id  INTEGER NOT NULL
);

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_id );

CREATE TABLE country (
    country_id    INTEGER NOT NULL,
    country_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_id );

CREATE TABLE department (
    department_id    INTEGER NOT NULL,
    department_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( department_id );

CREATE TABLE employee (
    employee_id           INTEGER NOT NULL,
    first_name            VARCHAR2(25) NOT NULL,
    last_name             VARCHAR2(25) NOT NULL,
    birth_date            DATE NOT NULL,
    gender                CHAR(1) NOT NULL,
    email                 CHAR(40) NOT NULL,
    position_position_id  INTEGER NOT NULL,
    address_address_id    INTEGER NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE employment_history (
    emp_dept_id               INTEGER NOT NULL,
    salary                    NUMBER NOT NULL,
    start_date                DATE NOT NULL,
    end_date                  DATE,
    employee_employee_id      INTEGER NOT NULL,
    department_department_id  INTEGER NOT NULL
);

ALTER TABLE employment_hsitory ADD CONSTRAINT employment_hsitory_pk PRIMARY KEY ( emp_dept_id );

CREATE TABLE position (
    position_id    INTEGER NOT NULL,
    position_name  VARCHAR2(50) NOT NULL
);

ALTER TABLE position ADD CONSTRAINT position_pk PRIMARY KEY ( position_id );

ALTER TABLE address
    ADD CONSTRAINT address_city_fk FOREIGN KEY ( city_city_id )
        REFERENCES city ( city_id );

ALTER TABLE city
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( country_country_id )
        REFERENCES country ( country_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_address_fk FOREIGN KEY ( address_address_id )
        REFERENCES address ( address_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_position_fk FOREIGN KEY ( position_position_id )
        REFERENCES position ( position_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE employment_history
    ADD CONSTRAINT emp_hist_department_fk FOREIGN KEY ( department_department_id )
        REFERENCES department ( department_id );

ALTER TABLE employment_history
    ADD CONSTRAINT emp_hist_employee_fk FOREIGN KEY ( employee_employee_id )
        REFERENCES employee ( employee_id );


CREATE OR REPLACE TRIGGER checkEmpAge
   BEFORE INSERT OR UPDATE ON employee
   FOR EACH ROW 
   declare date_diff_in_years number;
   begin  
    select (sysdate-:new.birth_date)/365.0 into date_diff_in_years from dual;
    if date_diff_in_years<18 then 
    RAISE_APPLICATION_ERROR (num => -20000,msg => 'Only adult people are allowed to work');
    end if;
   end;

create sequence emp_seq start with 1 increment by 1;

insert into employee values(emp_seq.nextval, 'abc','edf',to_date('12/03/2000','dd/mm/yyyy'),'M','abc@abc',1,1);


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0
